App.directive('loginForm',function(){
    return{
        restrict:'E',
        templateUrl:'templates/loginform.html',
        replace:true
    };
});
App.directive('tableMenu',function(){
    return{
        restrict:'E',
        templateUrl:'templates/tablemenu.html',
        replace:true
    };
});
App.directive('tableContent',function(){
    return{
        restrict:'E',
        templateUrl:'templates/table.html',
        replace:true
    };
});
App.directive('usersMenu',function(){
    return{
        restrict:'E',
        templateUrl:'templates/usersmenu.html',
        replace:true
    };
});
App.directive('userPrivileges',function(){
    return{
        restrict:'E',
        templateUrl:'templates/userprivilegestable.html',
        replace:true
    };
});
App.directive('userSettings',function(){
    return{
        restrict:'E',
        templateUrl:'templates/usersettings.html',
        replace:true
    };
});
App.directive('createUser',function(){
    return{
       restrict:'E',
       templateUrl:'templates/createuser.html',
       replace:true
    };
});
App.directive('addRow',function(){
    return{
        restrict:'E',
        templateUrl:'templates/addrow.html',
        replace:true
    };
});
App.directive('userInherit',function(){
    return{
        restrict:'E',
        templateUrl:'templates/userinherit.html',
        replace:true
    };
});
App.directive('queryMenu',function(){
    return{
        restrict:'E',
        templateUrl:'templates/querymenu.html',
        replace:true
    };
});
App.directive('queryContent',function(){
    return{
        restrict:'E',
        templateUrl:'templates/querycontent.html',
        replace:true
    };
});


